#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

.PHONY: all clean html

# All files which the build depends on
MD_FILES=$(shell find "./src" -name "*.md")
RST_FILES=$(shell find "./src" -name "*.rst")
PNG_FILES=$(shell find "./src" -name "*.png")
PROPERTIES_TEMPLATES=$(shell find "./src" -name "*.properties.in")

# Files that are automatically generated by the build
GENERATED_FILES += $(PROPERTIES_TEMPLATES:.properties.in=.properties.md)
GENERATED_FILES += $(PROPERTIES_TEMPLATES:.properties.in=.environment.md)
GENERATED_FILES += $(PROPERTIES_TEMPLATES:.properties.in=.example.properties)
GENERATED_FILES += $(PROPERTIES_TEMPLATES:.properties.in=.example.yml)
GENERATED_FILES += $(PROPERTIES_TEMPLATES:.properties.in=.example.txt)

#
# Build entire manual
#

all: html

#
# Clean build artifacts
#

clean:
	$(RM) -R build/ $(GENERATED_FILES)

#
# Automatic generation of property documentation/examples
#

%.properties.md: %.properties.in
	./generate-conf-docs.pl --mode=property-docs $< > $@

%.environment.md: %.properties.in
	./generate-conf-docs.pl --mode=environment-docs $< > $@

%.example.properties: %.properties.in
	./generate-conf-docs.pl --mode=property-example $< > $@

%.example.yml: %.properties.in
	./generate-conf-docs.pl --mode=docker-compose-example $< > $@

%.example.txt: %.properties.in
	./generate-conf-docs.pl --mode=docker-command-example $< > $@

#
# HTML manual build
#

html: build/html/index.html

build/html/index.html: $(PNG_FILES) $(RST_FILES) $(MD_FILES) $(GENERATED_FILES)
	sphinx-build -b html -d build/doctrees src/ build/html

